### ISSUE TITLE
About training RE-ID model by VeRi dataset

### ISSUE THREAD

**Issue by YuPeize** [cw1204772/AIC2018_iamai#1]
I used `create_VeRi_database.py` to process the VeRi dataset and then I did `python train.py --info VeRi_train_info.txt --lr 0.001 --batch_size 64 --n_epochs 20 --n_layer 18 --dataset VeRi` to train the model but the following error was encountered, why?

```
total data: 37746
training data: 35858
validation data: 1888
Epoch 0:   3%|█▎                                   | 1216/35858 [00:03<01:01, 566.62it/s, loss=6.35]Traceback (most recent call last):
  File "/home/ypz/pycharmfiles/AIC2018_iamai/ReID/ReID_CNN/train.py", line 331, in <module>
    train(args,Dataset,train_Dataloader,val_Dataloader,net)
  File "/home/ypz/pycharmfiles/AIC2018_iamai/ReID/ReID_CNN/train.py", line 96, in train
    for i_batch,samples in enumerate(train_Dataloader):
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 210, in __next__
    return self._process_next_batch(batch)
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 230, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 42, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 42, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ypz/pycharmfiles/AIC2018_iamai/ReID/ReID_CNN/utils.py", line 238, in __getitem__
    img_name,label = self.img_list[idx],self.label_list[idx]
IndexError: list index out of range

```

**Comment by YuPeize** [comment]
Uh, I solved it. There was a small problem for the dataset.

**Comment by cw1204772** [comment]
I'm glad you figure it out!
