### ISSUE TITLE
No module named core.config

### ISSUE THREAD

**Issue by rakhecha42** [cw1204772/AIC2018_iamai#4]
I'm trying to run.sh with the model file linked in the rep. This is the error I get. I already added the pythonpath for detectron to my bashrc. 

`[Detection]
Finish converting 1 / 1 video seqences into images
Traceback (most recent call last):
  File "tools/infer_simple_txt.py", line 38, in <module>
    from core.config import assert_and_infer_cfg
ImportError: No module named core.config
`

**Comment by rakhecha42** [comment]
okay so that got solved when i make installed the lib directory of this repo. But now i get this when I run.sh

`[Detection]
Finish converting 1 / 1 video seqences into images
Traceback (most recent call last):
  File "tools/infer_simple_txt.py", line 43, in <module>
    import core.test_engine as infer_engine
  File "/home/vadmin/AIC2018_iamai/Detection/lib/core/test_engine.py", line 35, in <module>
    from core.rpn_generator import generate_rpn_on_dataset
  File "/home/vadmin/AIC2018_iamai/Detection/lib/core/rpn_generator.py", line 42, in <module>
    from datasets import task_evaluation
  File "/home/vadmin/AIC2018_iamai/Detection/lib/datasets/task_evaluation.py", line 45, in <module>
    import datasets.cityscapes_json_dataset_evaluator as cs_json_dataset_evaluator
  File "/home/vadmin/AIC2018_iamai/Detection/lib/datasets/cityscapes_json_dataset_evaluator.py", line 28, in <module>
    import pycocotools.mask as mask_util
  File "build/bdist.linux-x86_64/egg/pycocotools/mask.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/pycocotools/_mask.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/pycocotools/_mask.py", line 6, in __bootstrap__
  File "__init__.pxd", line 918, in init pycocotools._mask
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
`

**Comment by cw1204772** [comment]
It seems like a problem in the installation of Detectron.
Perhaps you should first run the demo of Detectron to check if the installation is ok.
